version: '3'

services:
  ws0:
    build: .
    volumes:
      - .:/app
    command: "yarn start"
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  ws1:
    build: .
    volumes:
      - .:/app
    command: "yarn start"
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  redis:
    image: redis:6.2-alpine
    container_name: redis
    hostname: redis

  redis-admin:
    image: rediscommander/redis-commander
    container_name: redis-commander
    hostname: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8000:8081"
